on:
  push:
    branches:
      - 3.6.0_cbom
  workflow_dispatch:

jobs:
  cbom-scan:
    runs-on: ubuntu-latest
    name: CBOM generation
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 3.6.0_cbom # Ensure the correct branch is checked out

      - name: Create CBOM
        uses: PQCA/cbomkit-action@v1.1.0
        id: cbom
        continue-on-error: true

      - name: Create and publish CBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: "CBOM"
          path: cbom.json
